### ISSUE TITLE
大佬，我在AndroidStudio3.1.2导入，跑不起来，搞了半天了

### ISSUE THREAD

**Issue by tpnet** [dingjibang/GDX-RPG#22]
现在搞成这样子了，不知道是哪个冲突

![image](https://user-images.githubusercontent.com/17380722/41139261-23797d68-6b19-11e8-8a81-dc0410ae2628.png)

![image](https://user-images.githubusercontent.com/17380722/41139275-329d9dba-6b19-11e8-914b-955d3312cac3.png)

**Comment by dingjibang** [comment]
看到了，在吃午饭hhh，回去帮你研究一下

**Comment by dingjibang** [comment]
把grooid取消注释，安卓需要grooid才可以运行（groovy的安卓版），把grooid下面那行groovy删除，不要使用gradle配置里以外的groovy版本，因为没测试过

**Comment by tpnet** [comment]
@dingjibang  注释之后 ，，又报这样子的错误了

![image](https://user-images.githubusercontent.com/17380722/41282502-caefb350-6e66-11e8-8751-475ea2248f5c.png)

**Comment by dingjibang** [comment]
兄dei，[https://github.com/dingjibang/GDX-RPG/blob/master/build.gradle](https://github.com/dingjibang/GDX-RPG/blob/master/build.gradle)这里怎么写，你就这么写，直接复制这里的粘贴到你编辑器里

**Comment by dingjibang** [comment]
已解决
