### ISSUE TITLE
加油,我在关注你

### ISSUE THREAD

**Issue by MeDeity** [dingjibang/GDX-RPG#23]
国内用这个引擎的好像不多.国外就不知道了

**Comment by dingjibang** [comment]
谢谢关注呀兄弟
目前我个人主要把精力用在 https://github.com/dingjibang/GDX-HTML 这个项目上，目的是让开发者直接用html+css来构建libgdx，当做完时候这个项目我就可以继续开工了😄

**Comment by sunmes** [comment]
也算是偶尔会看看,也算是有关注有段时间了,作者Blog现在貌似挂了..
不过我感觉作者可能有点走偏了...
不过总之加油吧~

**Comment by dingjibang** [comment]
感谢关注，其实不配被关注
博客的话太久没更新了，mysql我也没开启所以首页打不开

至于这个项目写了几年我都不知道了，可能四五年了吧，那个时候libgdx正值火热，国内可能没什么太大动向，国外的话还是有很高热度的，但是这个热度也就持续几年，在18年之后这个框架也就慢慢冷却了，原因真的很简单，他不适合工业生产，虽然这个框架功能看起来齐全，但是缺少太多配套玩意了（所以叫框架不叫引擎），而且官方一两年也不在更新这个东西了，官方在issues里也说过，这个框架已经“毕业”成型了，不需要在往里面塞东西了，这种固步自封真不是啥好做法，我有时候挺希望官方那帮人能出来个libgdx2.0在火热一把

当然上面说的都是上游的东西，再说回这个项目，这个项目是当初和一群小伙伴打算做一款东方同人游戏，但是你也知道这玩意真的没法约束，一个人做游戏和一群人不一样，意见和分歧太多，进度也走不了多久，当然这和我也有很大关系，我负责拉这群人来做，结果也就慢慢弃坑了，这个锅肯定是我的，这群小伙伴包括我都是工作的人，没有那么多空闲时间，想写的很多也没法写太多，总之各种因素吧……这个项目就一直搁置着

而我作为一个码农只能做自己最本分的事情，就是一直一直的往这个项目里添砖加瓦，这1000多个commit都是实打实的代码，我也从一个0游戏开发经验摸爬滚打出来，这个项目更类似一个我的试验品，我本想抽出来做一个真正的RPG引擎，包括帮助文件，包括可视化的道具、素材、任务、敌人、AI、脚本编辑器（在[extension文件夹](https://github.com/dingjibang/GDX-RPG/tree/master/extension)里这些都差不多写完了），让大家用起来，但是那显然也不现实，因为这个RPG引擎的定位和libgdx一样，都只是个不能工业生产的东西，就算做完了也没人闲的会用hhh那些什么rpg maker之类的他不香吗

所以这个项目真心不值得关注，曾经做游戏的那群伙伴也都散了，就剩我一个铁孤儿在这守着这个框架了，我也没什么动力写下去了，我真的在这里投入了大把大把心血，这个项目像是我的黑历史hhh，但是看到1000多条commits，我还是能闭眼就想到当初下班、午休、周末通宵来实现整个RPG框架一个一个功能时，那种煎熬和快感（写出来东西时候还是很快乐的，这也是驱动我写下去的主要动力）

如果仍然以学习libgdx的态度来看这个项目，也可以随时联系我（也有不少人联系过我了，每次我都会很耐心的讲解这里面的代码），但如果是期待这个项目有新进展，那恐怕我也写不动了，项目凉了，libgdx也死掉了，我也没什么动力了。

**Comment by sunmes** [comment]
关注纯粹只是有点感兴趣就点个赞的形式.所有也没什么配不配的问题.

嗯,libgdx确实官方是没啥更新了.官网最近的版本貌似都不是官方人员处理的.貌似是从1.9.8版本开始?感觉和libgdx相关最火的可能不是游戏,而是Spine这个骨骼动画制作软件.工业生产这个我就不清楚了,不过我现在所在的公司的大部分项目倒是用的这个(我来这个公司的原因libgdx也算是一个理由),不过也都只是些休闲小游戏，但是也确实合适。
与其说东西多了，有时候我到觉得多余的东西多了。要是能有更精简的core，可能会更好一点。
很久以前也尝试了解过lwjgl，不过也只是浅尝则止，最终还是变成了OpenGL相关的内容，不过lwjgl本来就是OpenGL的Java绑定的一套处理方案。
JOGL貌似一直都没发展起来？也可能是我接触得太少。
虽然lwjgl桌面处理还不错，但是终究做桌面游戏还需要java这个运行环境，就还是不太合适(尤其新版本Java越来越大，虽然Java9能自定义Jre，但是似乎总还是不够小，甚至还不如1.6的.我甚至有尝试想要用1.0的jre。不过下载都是个问题)。
终究还是因为Java用得多，更习惯于此语言。

做成一个项目本身确实不容易，不仅仅是环境，还有自身的干劲。能坚持这么久已经不错了。坚持有时候就感觉是一种折磨..我也有小的圈子，建立初也是做游戏，不过我不是发起者而是参与人，而且参与内容和程序无关(画UI ，水平也就那样)。第一个游戏还算是很顺利的完成了(《这里没有格林达姆》)，也算是天时地利人和。 之后群里有尝试过好几个项目，最终一个都没成。我自己也有想过要做点什么，但是业余时的干劲只有三分钟热度。这么多年，终究还是玩游戏浪费了。

做轮子也是写程序的乐趣，尤其是上班的时候，重构，写工具，我感觉比做项目本身更有意思。不过这种机会还是比较少。业余了，又没了干劲。我对游戏还是很感兴趣的，也算是尝试过各种工具吧..
libgdx改一改，还是很有潜力的，毕竟Spine的实例就很不错。不过想归想，说归说，做归做。
我也顶多只是想想的程度罢了。

这个项目除了RPGMaker那种游戏内的形式(方格地图+方格人物)，其它的立绘UI效果都感觉还不错。不过没想到小伙伴们已经散了...我关注这个，一来是我也算是比较喜欢libgdx这套东西吧(虽然只用很基础的一部分东西，scenes2d这块也就Stage，Actor，Listener，Image，Group，ScrollPane. 其它的一些我现在都没去了解, Group这类我个人觉得Cocos那套Layer，Node更好。还有Unity里的那套坐标处理。), 二来，说明话语Blog之类的还算有趣，项目本身也稍微有那么点兴趣。

程序相关的，大概可能是理念不同，我也没怎么看项目的代码就是了。我个人更倾向于简易化统一化调用，大概就是更多的封装..

之所以觉得你走偏了也是如此，再一个可能是我觉得前端HTML那套本来就不太好(JavaFX也是这么一套，界面可以很华丽，但是总体而言用处不大，感觉不太实用。那个啥啥Builder就实在多了..),虽然我对JavaScript还是觉得很不错的，但是CSS那套就感觉有点不喜了。不过，也是每个人口味都不同吧。

Libgdx界面可视的编辑工具以前貌似有个O啥啥UI，也是坑了，不过之前看感觉也不是很好用，但也算不错了。

也只能说时代的车轮滚滚向前,时间的流逝一往无前。Java都到十几的版本了，我还遵循着1.6的那套规则，1.7的范型省略都不用.

不过工具始终只是工具。游戏本身才应该是目的。

**Comment by MeDeity** [comment]
没想到issue复活了.
这里我也说一下,其实我很早以前也在关注这个框架,因为懂java嘛,但是由于工作以及自学能力的原因.没吃透,我觉得,真的对游戏开发感兴趣的话,真的建议直接换个成熟点的游戏引擎.比如U3D,虚幻等等

**Comment by MeDeity** [comment]
另外业余项目能搞成这样,真的,我已经在膜拜了.
