### ISSUE TITLE
gradle报错Failed to resolve: org.mozilla:rhino:1.7.8-SNAPSHOT

### ISSUE THREAD

**Issue by zengaorong** [dingjibang/GDX-RPG#25]
ERROR: Failed to resolve: org.mozilla:rhino:1.7.8-SNAPSHOT

**Comment by dingjibang** [comment]
已修复，顺便可以[切换到这个分支，是以前版本，比较丰富](https://github.com/dingjibang/GDX-RPG/commit/1af96d38592a9c686b65695340c449f7968e46a2)
